### PR TITLE
Some notes on higher order methods.

### PR DESCRIPTION
**Pull request by IanHawke**
Concentrates on WENO.

Linked to https://github.com/zingale/pyro2/pull/21

Needs figures, the notation improving to match the other notes, cross-references to the other section to match up (which needs added labels in other chapters). Should probably be split in two  to put the nonlinear parts later.

### CODE REVIEW

**Comment by zingale** [comment]
Hi Ian, I deferred this until I got to this point in my class this semester (which is now), so I am of better mind to review.  Thanks again for the text -- this is a nice complement to what I have there.

Some comments:

  * It is not clear to me if this should be a stand-alone chapter or a new section in Ch. 4.  At the moment, the chapters are all based on physics / math topic, not numerical topics.  And this kinda breaks the trend

  * Can you use `a` instead of `q` as the advected quantity to match with Ch 4?

  *   Section 5.4 should appear after the Burgers eq section, again, keeping the progression by physics / math topic

 * Can you add a convergence plot like figure 4.14?

  * I am not sure I agree about the F-V timestep restriction (although, I confess that timestep restrictions get very tricky).  I coded up a 4th order F-V method in pyro now (`advection_fv4`) that you can compare to, and it's timestep is not more restrictive than the 2nd order MOL method already in there.  I plan to add some text about that in due time, so the question would be whether it integrates into here or a section in Ch. 4 along with this.

  * is the code for the figures available?  One goal I am working toward is making a link at every figure that takes you to the code to reproduce that figure.  A lot are in place.


Finally, please indicate how to properly credit you by adding your name to the title page and /or author page.

**Comment by IanHawke** [comment]
Hi Mike,
Also being clobbered by the start of semester here, so will keep this brief and update when possible.

1. Agree on the text; will create new chapters and split the linear/nonlinear parts.
2. Will switch to use `a` instead of `q`. Now have to work out what notation to use for the `a` coefficients (Shu calls them `c`, but that's also already gone).
3. Will work on a convergence plot. It won't be clean as the time integrator tends to saturate the errors rapidly. I don't have the lSSPRK methods implemented so will stick with RK4, so we'll see it limiting to fourth order. Something like this (which I'll push to my fork of `hydro_examples`)? Still not convinced there isn't an off-by-one here:
weno_convergence
4. On the timestep restriction: I tend to be guided by the statements from Shu's review or by the Gottlieb, Ketcheson and Shu review from 2008 (https://link.springer.com/article/10.1007%2Fs10915-008-9239-z). This is all for higher order in time using MoL. It may not generalise well, so it may be better to remove it from here for now.
5. The code for the figures should be part of the commit; `figures/weno/weno.py` produces a pile of figures but only saves to file those that I included.
6. Will sort the author thing.

**Comment by IanHawke** [comment]
Forgot to add in the above. See https://github.com/IanHawke/numerical_exercises/tree/weno_evolve/higher-order for notebooks deriving the coefficients and a toy evolution notebook with convergence plot showing the saturation.

To match up with the other examples (a bit) I pushed to https://github.com/IanHawke/hydro_examples/blob/weno/advection/weno.py which I'm not yet convinced by but probably shows the same thing.

We *might* be able to get around this by putting the CFL down to something absurdly small; in certain cases that minimizes the time evolution error.

**Comment by IanHawke** [comment]
In passing I note the following figure:
[weno-converge-small-cfl-2.pdf](https://github.com/Open-Astrophysics-Bookshelf/numerical_exercises/files/1391876/weno-converge-small-cfl-2.pdf)
This ran for 5 days (!) using a CFL of 5e-3 to minimize the time discretization error. I think the 5th order convergence is clean for r=3 (but then it looks ok for the standard case anyway), the 7th order ok for r=9 (but probably isn't too bad for similar points above), and the 9th order for r=5 isn't great beyond the first couple of points anyway.

So reducing the timestep doesn't seem to make enough difference to be helpful.

**Comment by IanHawke** [comment]
Hi Mike,

I think the latest commits mostly, but not completely, address the points you've asked for above: if you could skim this again I'd be grateful.

Things I haven't done (or not done well):

1. there's comments about systems at the end of the Burgers' chapter, at the end of the WENO part there. These are so brief that I'm not sure how they'd fit later on. Would be best to do a WENO-Euler for comparison, but I'm short of time for porting to the compiled code you use in the Euler section.
2. The convergence results using WENO+scipy DoPRK8 are a bit odd - it seems to lose an order somewhere. It's a useful plot in that is shows you can remove (or sufficiently reduce) the time integrator error, but I don't have an explanation for the precise convergence rates. The code is a bit of a hack, so if you can spot a cleaner way of doing this, it may be it's fixable.
3. I added the Gottlieb et al review to the refs.bib file, but it could really do with a brief section on the time integrators to actually cite it in. However, that may be overkill.

**Comment by zingale** [comment]
Great! I'll try to get to it this weekend.

**Comment by zingale** [comment]
This looks good, and I am happy to merge.  One minor change, section 4.9 (pyro exploration) and section 5.3 (going further) should probably both come at the end of their respective chapters.  We can change that post-merge. 

Now I need to learn me some WENO.

**Pull request merged**
